//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consoleservice.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ponto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Ponto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PontoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PontoId {
            get {
                return this.PontoIdField;
            }
            set {
                if ((this.PontoIdField.Equals(value) != true)) {
                    this.PontoIdField = value;
                    this.RaisePropertyChanged("PontoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProdutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnpjField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((this.ProdutoIdField.Equals(value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.NotaField, value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cnpj {
            get {
                return this.CnpjField;
            }
            set {
                if ((object.ReferenceEquals(this.CnpjField, value) != true)) {
                    this.CnpjField = value;
                    this.RaisePropertyChanged("Cnpj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensagem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Mensagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MensangemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        private int CodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MensangemId {
            get {
                return this.MensangemIdField;
            }
            set {
                if ((this.MensangemIdField.Equals(value) != true)) {
                    this.MensangemIdField = value;
                    this.RaisePropertyChanged("MensangemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.validapontosSoap")]
    public interface validapontosSoap {
        
        // CODEGEN: Generating message contract since element name ListaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lista", ReplyAction="*")]
        consoleservice.ServiceReference1.ListaResponse Lista(consoleservice.ServiceReference1.ListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Lista", ReplyAction="*")]
        System.Threading.Tasks.Task<consoleservice.ServiceReference1.ListaResponse> ListaAsync(consoleservice.ServiceReference1.ListaRequest request);
        
        // CODEGEN: Generating message contract since element name produto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastra", ReplyAction="*")]
        consoleservice.ServiceReference1.CadastraResponse Cadastra(consoleservice.ServiceReference1.CadastraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Cadastra", ReplyAction="*")]
        System.Threading.Tasks.Task<consoleservice.ServiceReference1.CadastraResponse> CadastraAsync(consoleservice.ServiceReference1.CadastraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Lista", Namespace="http://tempuri.org/", Order=0)]
        public consoleservice.ServiceReference1.ListaRequestBody Body;
        
        public ListaRequest() {
        }
        
        public ListaRequest(consoleservice.ServiceReference1.ListaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaRequestBody {
        
        public ListaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaResponse", Namespace="http://tempuri.org/", Order=0)]
        public consoleservice.ServiceReference1.ListaResponseBody Body;
        
        public ListaResponse() {
        }
        
        public ListaResponse(consoleservice.ServiceReference1.ListaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consoleservice.ServiceReference1.Ponto[] ListaResult;
        
        public ListaResponseBody() {
        }
        
        public ListaResponseBody(consoleservice.ServiceReference1.Ponto[] ListaResult) {
            this.ListaResult = ListaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Cadastra", Namespace="http://tempuri.org/", Order=0)]
        public consoleservice.ServiceReference1.CadastraRequestBody Body;
        
        public CadastraRequest() {
        }
        
        public CadastraRequest(consoleservice.ServiceReference1.CadastraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consoleservice.ServiceReference1.Produto produto;
        
        public CadastraRequestBody() {
        }
        
        public CadastraRequestBody(consoleservice.ServiceReference1.Produto produto) {
            this.produto = produto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastraResponse", Namespace="http://tempuri.org/", Order=0)]
        public consoleservice.ServiceReference1.CadastraResponseBody Body;
        
        public CadastraResponse() {
        }
        
        public CadastraResponse(consoleservice.ServiceReference1.CadastraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consoleservice.ServiceReference1.Mensagem[] CadastraResult;
        
        public CadastraResponseBody() {
        }
        
        public CadastraResponseBody(consoleservice.ServiceReference1.Mensagem[] CadastraResult) {
            this.CadastraResult = CadastraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface validapontosSoapChannel : consoleservice.ServiceReference1.validapontosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class validapontosSoapClient : System.ServiceModel.ClientBase<consoleservice.ServiceReference1.validapontosSoap>, consoleservice.ServiceReference1.validapontosSoap {
        
        public validapontosSoapClient() {
        }
        
        public validapontosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public validapontosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validapontosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validapontosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consoleservice.ServiceReference1.ListaResponse consoleservice.ServiceReference1.validapontosSoap.Lista(consoleservice.ServiceReference1.ListaRequest request) {
            return base.Channel.Lista(request);
        }
        
        public consoleservice.ServiceReference1.Ponto[] Lista() {
            consoleservice.ServiceReference1.ListaRequest inValue = new consoleservice.ServiceReference1.ListaRequest();
            inValue.Body = new consoleservice.ServiceReference1.ListaRequestBody();
            consoleservice.ServiceReference1.ListaResponse retVal = ((consoleservice.ServiceReference1.validapontosSoap)(this)).Lista(inValue);
            return retVal.Body.ListaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consoleservice.ServiceReference1.ListaResponse> consoleservice.ServiceReference1.validapontosSoap.ListaAsync(consoleservice.ServiceReference1.ListaRequest request) {
            return base.Channel.ListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<consoleservice.ServiceReference1.ListaResponse> ListaAsync() {
            consoleservice.ServiceReference1.ListaRequest inValue = new consoleservice.ServiceReference1.ListaRequest();
            inValue.Body = new consoleservice.ServiceReference1.ListaRequestBody();
            return ((consoleservice.ServiceReference1.validapontosSoap)(this)).ListaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consoleservice.ServiceReference1.CadastraResponse consoleservice.ServiceReference1.validapontosSoap.Cadastra(consoleservice.ServiceReference1.CadastraRequest request) {
            return base.Channel.Cadastra(request);
        }
        
        public consoleservice.ServiceReference1.Mensagem[] Cadastra(consoleservice.ServiceReference1.Produto produto) {
            consoleservice.ServiceReference1.CadastraRequest inValue = new consoleservice.ServiceReference1.CadastraRequest();
            inValue.Body = new consoleservice.ServiceReference1.CadastraRequestBody();
            inValue.Body.produto = produto;
            consoleservice.ServiceReference1.CadastraResponse retVal = ((consoleservice.ServiceReference1.validapontosSoap)(this)).Cadastra(inValue);
            return retVal.Body.CadastraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consoleservice.ServiceReference1.CadastraResponse> consoleservice.ServiceReference1.validapontosSoap.CadastraAsync(consoleservice.ServiceReference1.CadastraRequest request) {
            return base.Channel.CadastraAsync(request);
        }
        
        public System.Threading.Tasks.Task<consoleservice.ServiceReference1.CadastraResponse> CadastraAsync(consoleservice.ServiceReference1.Produto produto) {
            consoleservice.ServiceReference1.CadastraRequest inValue = new consoleservice.ServiceReference1.CadastraRequest();
            inValue.Body = new consoleservice.ServiceReference1.CadastraRequestBody();
            inValue.Body.produto = produto;
            return ((consoleservice.ServiceReference1.validapontosSoap)(this)).CadastraAsync(inValue);
        }
    }
}
